### ISSUE TITLE
Document safety guarantees

### ISSUE THREAD

**Issue by cite-reader** [selfup/rejs#13]
Currently, there are none. In particular, every time `fs.writeFileSync` is called, the backing file is re-opened with `O_TRUNC` on Linux, and presumably equivalent semantics on other operating systems. This is _incredibly dangerous,_ risking the loss or corruption of an entire "table" every time it's modified.

There's also no effort made to flush filesystem buffers. When operations return to the application, writes made may not yet have been persisted, possibly causing similar amounts of damage.

**Comment by selfup** [comment]
Thanks for the issue. Unfortunately I am using the fs module. Are there better methods to call from the fs module?

**Comment by selfup** [comment]
@JoshCheek 

Do you know how to help with this issue? Or is it a node/fs issue?

**Comment by cite-reader** [comment]
The simple way to achieve atomic file writes on POSIX is to write into a temporary file, then `rename(2)` the temporary into place. I assume Windows offers similar semantics, but I don't know that platform well enough to say.

Flushing filesystem buffers is accomplished through `fsync(2)`. A program can't do more than that, but an operator who _really cares_ will have to verify tor themselves that their filesystem and disks cooperate.

**Comment by selfup** [comment]
This helps wrap my head around this issue. But I have no idea what to do haha. This sounds like an fs module issue to me!

**Comment by cite-reader** [comment]
Those system calls are exposed through `fs`, but using the `fs.fsync` family requires raw file desciptors, which means going to `fs.open`, `fs.read`, etc etc.

**Comment by selfup** [comment]
Ohh interesting! I'll look into it when I have time. Thanks for being more thorough!

I am just surprised that it is so unsafe considering it is part of their official API.

**Comment by selfup** [comment]
I would recommend making an issue to Node itself. I should trust an API that is so popular. A lot of people use `fs.writeFileSync`

**Comment by selfup** [comment]
@cite-reader 

https://github.com/angular/angular-cli/search?utf8=%E2%9C%93&q=fs.writeFileSync

Here is an example of Google using it all over the place. Should I not trust what Google uses?

EDIT:

Ember uses it as well:

https://github.com/emberjs/ember.js/search?utf8=%E2%9C%93&q=writeFileSync&type=Code

So does yeoman:

https://github.com/yeoman/yo/search?utf8=%E2%9C%93&q=writeFileSync

The Atom text editor:

https://github.com/atom/atom/search?utf8=%E2%9C%93&q=writeFileSync

Electron:

https://github.com/electron/electron/search?utf8=%E2%9C%93&q=writeFileSync

React Native:

https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=writeFileSync

**Comment by selfup** [comment]
I am going to close this issue. The comment above this one proves that industry leaders use `fs.writeFileSync`.

Please forward this issue to Node itself!

**Comment by cite-reader** [comment]
The standards for things billing themselves as "databases" are higher. Or at least they should be.

If you don't want to put in the effort to be robust against power failure or what have you, that's a perfectly valid choice! But please at least be aware of what guarantees you offer, and then _document them_, so your users can be aware of them too.

**Comment by selfup** [comment]
That makes perfect sense. Thanks for making me aware. I will put it in my documentation for now. When I have time, I'll look into how to make it safer.

Thanks again for all of your help!

**Comment by selfup** [comment]
@cite-reader 

Updated my DOCS!

https://github.com/selfup/rejs/blob/master/DOCS.md

**Comment by cite-reader** [comment]
Hooray for documentation!
